/*
 * @Description:
 * @Author: L LC @amov
 * @Date: 2023-09-13 15:27:46
 * @LastEditors: L LC @amov
 * @LastEditTime: 2023-09-26 16:58:56
 * @FilePath: \SFP210-gimbal-powerControl\common\amovLink\src\amovlink_check.h
 */
#ifndef __AMOVLINK_CHECK_H
#define __AMOVLINK_CHECK_H

#include "stdint.h"

/**
 * "For each byte in the data, shift the CRC register left by 8 bits, XOR the CRC register with the CRC
 * table value for the byte, and then shift the CRC register right by 8 bits."
 *
 * The CRC table is a 256-byte array of 16-bit values.  The index into the table is the byte value.
 * The value in the table is the CRC value for that byte.  The CRC table is generated by the following
 * function:
 *
 * @param data pointer to the data to be checked
 * @param len the length of the data to be checked
 *
 * @return The CRC value.
 * @note 16 bit CRC with polynomial x^16+x^12+x^5+1
 */
uint16_t amovLinkCheckCrc16(uint8_t *data, uint32_t len);

#endif
